name: myop
channels:
  - conda-forge
  - defaults
  - bioconda
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.44=h9d8b0ac_5
  - binutils_linux-64=2.44=h4852527_5
  - boost=1.82.0=h8da182e_6
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - cmake=4.1.2=hc85cc9f_0
  - curl=8.17.0=h4e3cde8_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gcc_linux-64=12.4.0=h6b7512a_10
  - gfortran_impl_linux-64=12.4.0=h61783b2_2
  - git=2.49.0=pl5321h59d505e_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gtest=1.17.0=h84d6215_1
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - gxx_linux-64=12.4.0=h8489865_10
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libboost-devel=1.82.0=h00ab1b0_6
  - libboost-headers=1.82.0=ha770c72_6
  - libboost-python=1.82.0=py312hfb10629_6
  - libboost-python-devel=1.82.0=py312h8da182e_6
  - libcblas=3.9.0=38_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgit2=1.8.4=hd24f944_1
  - libglib=2.84.1=h2ff4ddf_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=12.4.0=ha732cd4_2
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=1.26.4=py312heda63a1_0
  - openssl=3.6.0=h26f9b46_0
  - pandoc=3.8.2.1=ha770c72_0
  - pango=1.54.0=h4c5309f_1
  - pcre2=10.44=hc749103_2
  - perl=5.22.0.1=0
  - perl-app-cpanminus=1.7043=pl5.22.0_0
  - perl-bioperl=1.6.924=4
  - perl-mce=1.835=pl5.22.0_0
  - perl-parallel-forkmanager=1.17=0
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-yaml=1.24=pl522_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.12.12=hfe2f287_0_cpython
  - python_abi=3.12=8_cp312
  - r-askpass=1.2.1=r44h54b55ab_1
  - r-assertthat=0.2.1=r44hc72bb7e_6
  - r-base=4.4.1=h0be853a_12
  - r-base64enc=0.1_3=r44h54b55ab_1008
  - r-brew=1.0_10=r44hc72bb7e_2
  - r-brio=1.1.5=r44h54b55ab_2
  - r-bslib=0.9.0=r44hc72bb7e_1
  - r-cachem=1.1.0=r44h54b55ab_2
  - r-callr=3.7.6=r44hc72bb7e_2
  - r-cli=3.6.5=r44h3697838_1
  - r-clipr=0.8.0=r44hc72bb7e_4
  - r-commonmark=2.0.0=r44h54b55ab_1
  - r-cpp11=0.5.2=r44h785f33e_2
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-credentials=2.0.3=r44hc72bb7e_1
  - r-curl=7.0.0=r44h10955f1_1
  - r-desc=1.4.3=r44hc72bb7e_2
  - r-devtools=2.4.6=r44hc72bb7e_0
  - r-diffobj=0.3.6=r44h54b55ab_1
  - r-digest=0.6.37=r44h3697838_1
  - r-downlit=0.4.4=r44hc72bb7e_2
  - r-ellipsis=0.3.2=r44h54b55ab_4
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.6=r44h54b55ab_2
  - r-fastmap=1.2.0=r44h3697838_2
  - r-fontawesome=0.5.3=r44hc72bb7e_1
  - r-fs=1.6.6=r44h3697838_1
  - r-gert=2.1.4=r44h017ce79_0
  - r-gh=1.5.0=r44hc72bb7e_1
  - r-gitcreds=0.1.2=r44hc72bb7e_4
  - r-glue=1.8.0=r44h54b55ab_1
  - r-highr=0.11=r44hc72bb7e_2
  - r-htmltools=0.5.8.1=r44h3697838_2
  - r-htmlwidgets=1.6.4=r44h785f33e_4
  - r-httpuv=1.6.16=r44h6d565e7_1
  - r-httr2=1.2.1=r44hc72bb7e_1
  - r-ini=0.3.1=r44hc72bb7e_1007
  - r-jquerylib=0.1.4=r44hc72bb7e_4
  - r-jsonlite=2.0.0=r44h54b55ab_1
  - r-knitr=1.50=r44hc72bb7e_1
  - r-later=1.4.4=r44h3697838_1
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-magrittr=2.0.4=r44h54b55ab_0
  - r-memoise=2.0.1=r44hc72bb7e_4
  - r-mime=0.13=r44h54b55ab_1
  - r-miniui=0.1.2=r44hc72bb7e_1
  - r-openssl=2.3.4=r44h50f7d53_0
  - r-otel=0.2.0=r44hc72bb7e_1
  - r-pillar=1.11.1=r44hc72bb7e_0
  - r-pkgbuild=1.4.8=r44hc72bb7e_1
  - r-pkgconfig=2.0.3=r44hc72bb7e_5
  - r-pkgdown=2.1.2=r44hc72bb7e_0
  - r-pkgload=1.4.1=r44hc72bb7e_0
  - r-praise=1.0.0=r44hc72bb7e_1009
  - r-prettyunits=1.2.0=r44hc72bb7e_2
  - r-processx=3.8.6=r44h54b55ab_1
  - r-profvis=0.4.0=r44h54b55ab_1
  - r-promises=1.5.0=r44hc72bb7e_1
  - r-ps=1.9.1=r44h54b55ab_1
  - r-purrr=1.2.0=r44h54b55ab_0
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-ragg=1.3.3=r44h9aa3752_0
  - r-rappdirs=0.3.3=r44h54b55ab_4
  - r-rcmdcheck=1.4.0=r44h785f33e_4
  - r-rcpp=1.1.0=r44h3697838_1
  - r-rematch2=2.1.2=r44hc72bb7e_5
  - r-remotes=2.5.0=r44hc72bb7e_2
  - r-rlang=1.1.6=r44h3697838_1
  - r-rmarkdown=2.30=r44hc72bb7e_0
  - r-roxygen2=7.3.3=r44h3697838_1
  - r-rprojroot=2.1.1=r44hc72bb7e_1
  - r-rstudioapi=0.17.1=r44hc72bb7e_1
  - r-rversions=3.0.0=r44hc72bb7e_0
  - r-sass=0.4.10=r44h3697838_1
  - r-sessioninfo=1.2.3=r44hc72bb7e_1
  - r-shiny=1.11.1=r44h785f33e_1
  - r-sourcetools=0.1.7_1=r44h3697838_3
  - r-stringi=1.8.4=r44ha8ce623_2
  - r-stringr=1.6.0=r44h785f33e_0
  - r-sys=3.4.3=r44h54b55ab_1
  - r-systemfonts=1.3.1=r44h74f4acd_0
  - r-testthat=3.2.3=r44h3697838_2
  - r-textshaping=0.4.0=r44ha47bcaa_2
  - r-tibble=3.3.0=r44h54b55ab_1
  - r-tinytex=0.57=r44hc72bb7e_1
  - r-urlchecker=1.0.1=r44hc72bb7e_4
  - r-usethis=3.2.1=r44hc72bb7e_1
  - r-utf8=1.2.6=r44h54b55ab_1
  - r-vctrs=0.6.5=r44h3697838_2
  - r-waldo=0.6.2=r44hc72bb7e_1
  - r-whisker=0.4.1=r44hc72bb7e_3
  - r-withr=3.0.2=r44hc72bb7e_1
  - r-xfun=0.54=r44h3697838_0
  - r-xml2=1.4.0=r44hc6fd541_1
  - r-xopen=1.0.1=r44hc72bb7e_2
  - r-xtable=1.8_4=r44hc72bb7e_7
  - r-yaml=2.3.10=r44h54b55ab_1
  - r-zip=2.3.3=r44h54b55ab_1
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
